version: '3.8'

services:
  # Основное приложение
  app:
    build:
      context: .
      dockerfile: OnlineSchool/Dockerfile
    container_name: online-school-app
    restart: unless-stopped
    networks:
      - app-network

  # Nginx с SSL
  nginx:
    image: nginx:alpine
    container_name: online-school-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge